# .github/actionlint.yaml

# Désactive l'intégration ShellCheck au niveau binaire (optionnel si ignore est complet)
shellcheck: ""

# Ignorer globalement les erreurs ShellCheck par message
ignore:
  - 'shellcheck reported issue in this script: SC2034'
  - 'shellcheck reported issue in this script: SC2129'
  - 'shellcheck reported issue in this script: SC2086'

# Configuration spécifique par fichier (si vous voulez être plus précis)
paths:
  ".github/workflows/harbor-deploy.yml":
    ignore:
      - 'SC2034'
  ".github/workflows/healthcheck-prod.yml":
    ignore:
      - 'SC2129'
      - 'SC2034'
  ".github/workflows/healthcheck-postdeploy.yml":
    ignore:
      - 'SC2129'
  ".github/workflows/securitycheck.yml":
    ignore:
      - 'SC2129'
