# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

config-variables: []

# Disable shellcheck integration in actionlint
shellcheck:
  enable: false

# Ignore shellcheck messages surfaced by actionlint (fallback)
ignore:
  - 'shellcheck reported issue in this script'
  - 'SC2034'  # variable appears unused (false positives in heredocs/ssh)
  - 'SC2129'  # multiple >> append style warning
  - 'SC2086'  # word splitting / globbing quoting advice
  - 'SC2154'  # referenced but not assigned warning (false positives in heredocs/ssh)
  - 'SC2317'  # useless use of cat warning
  - 'SC2006'  # use $(...) instead of legacy backticked `...` command substitution
  - 'SC2046'  # quote to prevent globbing and word splitting
  - 'SC2164'  # cd without -e check
