# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

config-variables: []

shellcheck:
  enable: false

ignore:
  - 'shellcheck reported issue in this script'
  - 'SC2034'
  - 'SC2129'
  - 'SC2086'
  - 'SC2154'
  - 'SC2317'
  - 'SC2006'
  - 'SC2046'
  - 'SC2164'
