# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

config-variables: []

# Ignore all shellcheck messages reported by actionlint (shellcheck disabled)
ignore:
  - 'shellcheck reported issue in this script'
