# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Disable shellcheck integration (use local shellcheck in CI instead)
shellcheck:

self-hosted-runner:
  labels: []

config-variables: []
