# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

config-variables: []

# Ignore all shellcheck messages reported by actionlint (shellcheck disabled)
ignore:
  - 'shellcheck reported issue in this script'  # blanket ignore from actionlint
  - 'SC2034'  # variable appears unused (false positives in heredocs/ssh)
  - 'SC2129'  # multiple >> append style warning
  - 'SC2086'  # word splitting / globbing quoting advice