# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Self-hosted runner configuration
self-hosted-runner:
  labels: []

config-variables: false

# Disable shellcheck integration to avoid info/style noise
# These warnings (SC2086, SC2129, SC2006) are acceptable in CI/CD contexts
shellcheck:
  enable: false
