# .github/actionlint.yaml

# IMPORTANT : L'option 'shellcheck: enable: false' n'existe pas dans le fichier YAML.
# Pour désactiver shellcheck globalement via la config, on utilise 'shellcheck: ""'
shellcheck: ""

# Ignorer globalement des erreurs par Regex
ignore:
  - 'shellcheck reported issue in this script: SC2034'
  - 'shellcheck reported issue in this script: SC2129'
  - 'shellcheck reported issue in this script: SC2086'
  # Pour tout couper si 'shellcheck: ""' ne suffit pas selon votre version :
  - 'shellcheck reported issue in this script:.*'

# Configuration spécifique par fichier
paths:
  ".github/workflows/harbor-deploy.yml":
    ignore:
      - 'SC2034'
  ".github/workflows/healthcheck-prod.yml":
    ignore:
      - 'SC2129'
      - 'SC2034'
  ".github/workflows/healthcheck-postdeploy.yml":
    ignore:
      - 'SC2129'
  ".github/workflows/securitycheck.yml":
    ignore:
      - 'SC2129'
