extends: default

rules:
  # Keep it strict on whitespace
  trailing-spaces: enable
  new-line-at-end-of-file: enable

  # Relax noisy checks
  line-length:
    max: 160
    allow-non-breakable-words: true
  document-start: disable
  truthy: disable
  comments: disable
