#!/bin/bash
# Production Registry Secrets Setup Script
# Run this to understand what secrets need to be created

echo "=========================================="
echo "🔐 Production Registry Credentials Setup"
echo "=========================================="
echo ""
echo "✅ Code Changes Completed:"
echo "   • Modified .github/workflows/registry-deploy.yml"
echo "   • Production job now uses: REGISTRY_USERNAME_PROD, REGISTRY_PASSWORD_PROD"
echo "   • Updated saas/registry/docker-compose.prod.yml"
echo ""
echo "⚠️  REQUIRED: Create GitHub Secrets"
echo "=========================================="
echo ""
echo "Go to: https://github.com/christophe-freijanes/freijstack/settings/secrets/actions"
echo ""
echo "Create these two secrets:"
echo "  1. REGISTRY_USERNAME_PROD"
echo "     Value: admin-prod (or your preferred username)"
echo ""
echo "  2. REGISTRY_PASSWORD_PROD"
echo "     Value: <strong random password>"
echo "     Example: $(openssl rand -base64 16 2>/dev/null || echo 'generate using openssl')"
echo ""
echo "=========================================="
echo ""
echo "Or use GitHub CLI:"
echo "  gh secret set REGISTRY_USERNAME_PROD --body 'admin-prod'"
echo "  gh secret set REGISTRY_PASSWORD_PROD --body '<password>'"
echo ""
echo "=========================================="
echo ""
echo "🚀 After creating secrets:"
echo "  1. Push to main branch: git push origin main"
echo "  2. Watch GitHub Actions: registry-deploy.yml"
echo "  3. Test: curl -u admin-prod:password https://registry.freijstack.com/v2/"
echo ""
echo "✅ Check healthcheck: healthcheck-prod.yml workflow"
echo ""
echo "📚 Documentation: docs-private/REGISTRY_PROD_CREDENTIALS.md"
echo "=========================================="
